'use client';
import Link from 'next/link';
import {ArrowRight,Sparkles,Check} from 'lucide-react';
import {SiteShell} from '@/components/site-shell';
import {Calculator} from '@/components/calculator';
import {Experts} from '@/components/experts';

import {Testimonials} from '@/components/testimonials';
import {usePublic} from '@/components/provider';
import {ReportCards} from '@/components/report-cards';
export default function Home(){const {data}=usePublic();const title=data?.settings.heroTitle;const customTitle=title&&title!=='A little clarity. A more intentional tomorrow.';return <SiteShell><div className="reference-home"><section className="reference-hero"><div className="container reference-hero-grid"><div className="reference-copy"><div className="reference-badge"><Sparkles size={14}/>{data?.settings.tagline||'NUMEROLOGY · ASTROLOGY · SELF-DISCOVERY'}</div><h1>{customTitle?title:'Check your Numbers'}</h1><p>{data?.settings.heroDescription&&data.settings.heroDescription!=='Explore the meaning in your numbers, find a moment of daily guidance, and discover a report made just for you.'?data.settings.heroDescription:'Discover the numbers in your date of birth. Get your birth number and life-path number, with a simple explanation of every calculation — no payment needed.'}</p><div className="reference-stats"><div><strong>Free</strong><span>Number discovery</span></div><div><strong>Personal</strong><span>Human-reviewed PDFs</span></div><div><strong>12–24 hrs</strong><span>After payment</span></div></div></div><Calculator/></div></section><section className="container reference-reports section" id="reports"><div className="reference-heading"><div className="eyebrow">PERSONALLY PREPARED BY {data?.settings.brand||'NUMEROVEDA'}</div><h2>Detailed Personal Reports</h2><p>Explore your name, birth date, and the questions that matter to you. Thoughtfully prepared, reviewed by a real person, and delivered as a PDF in 12–24 hours.</p></div><ReportCards/>{data&&!data.products.length&&<p className="notice">Report offerings will be published shortly.</p>}</section><Experts/><Testimonials/><section className="container reference-about section" id="about"><h2>About {data?.settings.brand||'NumeroVeda'}</h2><p>We bring a personal approach to numerology. Explore your numbers for free, or choose a personal report for your life, relationships, family, career, and business. Each report is prepared around your details and questions.</p><p>Your paid report is manually prepared and reviewed, then made available as a private PDF within 12–24 hours of verified payment.</p><div className="about-checks"><span><Check size={17}/> Clear calculations</span><span><Check size={17}/> Human-reviewed reports</span><span><Check size={17}/> Secure PDF access</span></div><Link href="/reports" className="button">Explore personal reports <ArrowRight size={17}/></Link></section></div></SiteShell>;}



