'use client';
import {useState} from 'react';
import {activeFields,reportDefinition} from '@/lib/report-catalog';
export function ReportIntake({productId,initialAnswers={}}:{productId:string;initialAnswers?:Record<string,string>}){
 const [answers,setAnswers]=useState<Record<string,string>>(initialAnswers);
 const definition=reportDefinition(productId);
 if(!definition)return <><label>Date of birth<input type="date" name="dob" required max={new Date().toISOString().slice(0,10)}/></label><label>Your questions<textarea name="question" rows={3} maxLength={3000}/></label></>;
 const fields=activeFields(productId,answers);
 return <section className="report-intake"><h3>About your report</h3><p className="small-copy">Fields marked * are required. Other details are optional.</p>{productId==='marriage-date'&&<p className="notice">Numerological date selection and astrological muhurat are different services. An actual muhurat requires both birth times and birthplaces and manual preparation by an astrologer.</p>}{productId==='relationship-compatibility'&&<p className="small-copy">Please share the other person’s details only with their permission.</p>}<div className="intake-fields">{fields.map(field=>{const value=answers[field.key]||'';const props={name:'intake.'+field.key,value,required:!!field.required,onChange:(e:React.ChangeEvent<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>)=>setAnswers(a=>({...a,[field.key]:e.target.value}))};if(field.type==='multi'){const selected=value?value.split(' | '):[];return <fieldset key={field.key} className="focus-options intake-wide"><legend>{field.label} *</legend>{field.options?.map(option=><label key={option}><input type="checkbox" checked={selected.includes(option)} required={!selected.length} disabled={selected.length>=3&&!selected.includes(option)} onChange={e=>setAnswers(a=>({...a,[field.key]:(e.target.checked?[...selected,option]:selected.filter(v=>v!==option)).join(' | ')}))}/>{option}</label>)}<input type="hidden" name={'intake.'+field.key} value={value}/></fieldset>;}return <label key={field.key} className={field.type==='textarea'?'intake-wide':''}>{field.label}{field.required?' *':' (optional)'}{field.type==='select'?<select {...props}><option value="">Select an option</option>{field.options?.map(option=><option key={option}>{option}</option>)}</select>:field.type==='textarea'?<textarea {...props} rows={3} maxLength={3000}/>:<input {...props} type={field.type||'text'} maxLength={3000} min={field.type==='number'?1900:field.type==='date'?'1900-01-01':undefined} max={field.type==='number'?2200:field.type==='date'&&!['dateFrom','dateTo'].includes(field.key)?new Date().toISOString().slice(0,10):undefined}/ >}{field.hint&&<span className="small-copy muted">{field.hint}</span>}</label>;})}</div></section>;
}
