'use client';
import Link from 'next/link';


import {Sun,ArrowUpRight,Mail,MessageCircle} from 'lucide-react';
import {usePublic} from './provider';
export function Brand(){const {data}=usePublic();return <Link href="/" className="brand" aria-label="Home"><span className="brand-mark"><Sun size={23} strokeWidth={1.3}/></span><span>{data?.settings.brand||'NumeroVedaa'}<small>THE ART OF SELF-DISCOVERY</small></span></Link>;}
export function SiteShell({children}:{children:React.ReactNode}){const {data,error}=usePublic();return <><a className="skip-link" href="#main">Skip to content</a><header className="site-header reference-header"><div className="container nav"><Brand/><Link className="report-access" href="/track"><span><small>Already Paid?</small>Access Report</span><ArrowUpRight size={18}/></Link></div></header>{error&&<div className="container"><p className="notice error" role="alert">We’re having trouble loading current content. Please refresh in a moment.</p></div>}<main id="main">{children}</main><footer className="site-footer"><div className="container footer-grid"><div><Brand/><p>{data?.settings.tagline||'Vedic numerologist offering personalised numerology reports based on your name and birth date.'}</p></div><div><h3>Company details</h3><p className="footer-detail">Name: {data?.settings.brand||'NumeroVedaa'}<br/>GST: <span className="footer-placeholder">[Add GST number]</span></p></div><div><h3>Contact us</h3>{data?.settings.phone?<a href={'https://wa.me/'+data.settings.phone.replace(/\D/g,'')} target="_blank" rel="noreferrer"><MessageCircle size={15}/>WhatsApp us</a>:<span className="muted footer-placeholder"><MessageCircle size={15}/>[Add WhatsApp number]</span>}{data?.settings.email?<a href={'mailto:'+data.settings.email}><Mail size={15}/>{data.settings.email}</a>:<span className="muted footer-placeholder"><Mail size={15}/>[Add support email]</span>}</div><div><h3>Policies</h3><Link href="/policies">Privacy Policy</Link><Link href="/policies">Terms &amp; Conditions</Link><Link href="/policies">Refund &amp; Cancellation Policy</Link><Link href="/policies">Shipping &amp; Delivery Policy</Link><Link href="/policies">Contact Us</Link><Link href="/#about">About Us</Link></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} {data?.settings.brand||'NumeroVedaa'}. All rights reserved.</span><Link href="/admin">Admin sign in</Link></div></footer></>;}



