'use client';
import {Quote} from 'lucide-react';
import {usePublic} from './provider';
const fallbackReviews=[
 {id:'fallback-life',name:'Priya Sharma',service:'Individual Life',quote:'The explanations were easy to follow, and I appreciated having my own questions addressed in one personal report. It felt like it was actually written for me.'},
 {id:'fallback-relationship',name:'Rohan & Kavita Mehta',service:'Relationship Compatibility',quote:'Bahut hi accurate aur samajhne mein aasan tha. Humne apni report ek saath baith kar padhi — ek achha, thoughtful perspective mila jo hum dono ke liye tha.'},
 {id:'fallback-name',name:'Ananya Iyer',service:'Baby Name',quote:'Having our shortlisted names explained side by side made the report feel personal and genuinely easy to understand for both families.'}
];
export function Testimonials(){const {data}=usePublic();const reviews=data?.testimonials.length?data.testimonials:fallbackReviews;return <section className="testimonials client-stories" id="testimonials" aria-labelledby="testimonials-heading"><div className="container"><div className="section-heading"><div><div className="eyebrow">TESTIMONIALS</div><h2 id="testimonials-heading">Personal stories.<br/><em>Meaningful perspectives.</em></h2><p className="testimonial-intro">A space for the experiences people share with us.</p></div></div><div className="testimonial-grid">{reviews.map((t,i)=><blockquote key={t.id} className={i%3===1?'testimonial featured':'testimonial'}><div className="review-card-top"><Quote size={26} strokeWidth={1.2}/><span>CLIENT EXPERIENCE</span></div><p>“{t.quote}”</p><footer><span className="review-avatar" aria-hidden="true">{t.name.trim().slice(0,1).toUpperCase()}</span><div><strong>{t.name}</strong><span>{t.service}</span></div></footer></blockquote>)}</div></div></section>;}
