'use client';
import {Quote} from 'lucide-react';
import {usePublic} from './provider';
const examples=[
 {id:'sample-life',name:'Example client',service:'Individual Life',quote:'The explanations were easy to follow, and I appreciated having my questions addressed in one personal report.'},
 {id:'sample-relationship',name:'Example client',service:'Relationship Compatibility',quote:'A thoughtful perspective on the questions we shared, with a report we could read and reflect on together.'},
 {id:'sample-name',name:'Example client',service:'Baby Name',quote:'Having our shortlisted names explained side by side made the report feel personal and easy to understand.'}
];
export function Testimonials(){const {data}=usePublic();const demo=!data?.testimonials.length;const reviews=demo?examples:data!.testimonials;return <section className="testimonials client-stories" id="testimonials" aria-labelledby="testimonials-heading"><div className="container"><div className="section-heading"><div><div className="eyebrow">TESTIMONIALS</div><h2 id="testimonials-heading">Personal stories.<br/><em>Meaningful perspectives.</em></h2><p className="testimonial-intro">A space for the experiences people share with us.</p></div></div>{demo&&<p className="sample-review-note">Sample testimonials for layout preview — not actual customer reviews.</p>}<div className="testimonial-grid">{reviews.map((t,i)=><blockquote key={t.id} className={i%3===1?'testimonial featured':'testimonial'}><div className="review-card-top"><Quote size={26} strokeWidth={1.2}/><span>{demo?'SAMPLE REVIEW':'CLIENT EXPERIENCE'}</span></div><p>“{t.quote}”</p><footer><span className="review-avatar" aria-hidden="true">{demo?'✧':t.name.trim().slice(0,1).toUpperCase()}</span><div><strong>{t.name}</strong><span>{t.service}</span></div></footer></blockquote>)}</div></div></section>;}
