import {activeFields} from '../lib/report-catalog';
import express from 'express';
import cookieParser from 'cookie-parser';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import multer from 'multer';
import sharp from 'sharp';
import {randomBytes,randomUUID} from 'node:crypto';
import {writeFileSync,readFileSync} from 'node:fs';
import path from 'node:path';
import {z,ZodError} from 'zod';
import {db,dataDir,settings,entries,saveEntry,allOrders,getOrder,saveOrder,audit} from './db';
import {hash,passwordHash,passwordMatches,requireAdmin,originGuard} from './security';
import {schemas,settingsSchema,orderSchema} from './schemas';
import {createPayment,verifyPayment,validWebhook,paymentConfigured,paymentMode} from './payments';
import {sendMail,mailConfigured} from './mail';
import type {Entry,Kind,Order,OrderStatus,Product} from '../lib/types';
const fail=(message:string,status=400)=>Object.assign(new Error(message),{status});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024,files:1,fields:5}});
const kindOf=(value:string):Kind=>{if(!Object.hasOwn(schemas,value))throw fail('Unknown content type.',404);return value as Kind;};
function accessible(req:express.Request):Order{const id=String(req.params.id);const token=req.headers.authorization?.replace(/^Bearer /,'')||'';if(!token||token.length>200)throw fail('Enter your order number and access code.',401);const row=db.prepare('SELECT access_hash FROM orders WHERE id=?').get(id) as {access_hash:string}|undefined;if(!row||hash(token)!==row.access_hash)throw fail('Order number or access code is incorrect.',404);return getOrder(id)!;}
function publicOrder(order:Order){const {internalNote,reportFile,cashfreeSession,...safe}=order;return {...safe,hasReport:!!reportFile&&order.status==='delivered'};}
export function createApp(){
 const app=express();app.disable('x-powered-by');app.use(helmet({contentSecurityPolicy:false}));app.use(cookieParser());
 app.use('/api',(_req,res,next)=>{res.setHeader('Cache-Control','no-store');next();});
 app.post('/api/payments/cashfree/webhook',express.raw({type:'application/json',limit:'256kb'}),async(req,res)=>{
  if(!Buffer.isBuffer(req.body)||!validWebhook(req.body,String(req.headers['x-webhook-timestamp']||''),String(req.headers['x-webhook-signature']||'')))return res.status(401).json({error:'Invalid signature.'});
  const event=JSON.parse(req.body.toString());const id=event?.data?.order?.order_id;
  if(typeof id==='string'&&getOrder(id))await verifyPayment(id);
  res.json({received:true});
 });
 app.use(express.json({limit:'128kb'}));app.use(originGuard);
 const authLimit=rateLimit({windowMs:15*60*1000,limit:20,standardHeaders:'draft-8',legacyHeaders:false,message:{error:'Too many attempts. Please try again in 15 minutes.'}});
 const publicLimit=rateLimit({windowMs:15*60*1000,limit:120,standardHeaders:'draft-8',legacyHeaders:false,message:{error:'Too many requests. Please try again shortly.'}});
 app.get('/api/health',(_req,res)=>res.json({ok:true}));
 app.get('/api/public',(_req,res)=>{const published=(kind:Kind)=>entries(kind).filter(x=>x.published).sort((a,b)=>Number(a.order||0)-Number(b.order||0));res.json({settings:settings(),products:published('products'),experts:published('experts'),testimonials:published('testimonials'),panchang:published('panchang').map(({source,...p})=>p),horoscopes:published('horoscopes'),payment:{configured:paymentConfigured(),enabled:settings().paymentsEnabled,mode:paymentMode()}});});
 app.get('/api/media/:file',(req,res)=>{if(!/^[a-f0-9-]+\.webp$/.test(req.params.file))throw fail('Image not found.',404);res.setHeader('Cache-Control','public,max-age=86400');res.sendFile(path.join(dataDir,'images',req.params.file));});
 app.post('/api/auth/login',authLimit,(req,res)=>{const input=z.object({email:z.email(),password:z.string().min(1).max(200)}).parse(req.body);const user=db.prepare('SELECT * FROM users WHERE email=?').get(input.email.toLowerCase()) as {id:string;password:string}|undefined;const dummy='00'.repeat(16)+':'+'00'.repeat(64);if(!passwordMatches(input.password,user?.password||dummy)||!user)throw fail('Email or password is incorrect.',401);db.prepare('DELETE FROM sessions WHERE expires<?').run(Date.now());const token=randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(hash(token),user.id,Date.now()+8*3600000);res.cookie('nv_admin',token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'strict',path:'/',maxAge:8*3600000});audit('admin.login',user.id);res.json({ok:true});});
 app.post('/api/auth/logout',(req,res)=>{if(req.cookies.nv_admin)db.prepare('DELETE FROM sessions WHERE hash=?').run(hash(req.cookies.nv_admin));res.clearCookie('nv_admin',{path:'/',httpOnly:true,sameSite:'strict',secure:process.env.NODE_ENV==='production'});res.json({ok:true});});
 app.get('/api/auth/me',requireAdmin,(_req,res)=>res.json({authenticated:true}));
 app.post('/api/report-intake/validate',publicLimit,(req,res)=>{const input=orderSchema.parse(req.body);if(!entries('products').some(p=>p.id===input.productId&&p.published))throw fail('This report is not available.',404);res.json({ok:true});});
 app.post('/api/orders',publicLimit,async(req,res)=>{const input=orderSchema.parse(req.body);if(!settings().paymentsEnabled||!paymentConfigured())throw fail('Online payments are not open yet. Please contact us or check back shortly.',503);const product=entries('products').find(p=>p.id===input.productId&&p.published) as Product|undefined;if(!product)throw fail('This report is not available.',404);const answers:Record<string,string>={...input.answers,dob:input.answers.dob||input.dob,question:input.answers.question||input.question};const intake=activeFields(product.id,answers).filter(f=>answers[f.key]).map(f=>({label:f.label,value:answers[f.key]}));const token=randomBytes(24).toString('hex');const id='NV_'+randomBytes(10).toString('hex');const order:Order={id,productId:product.id,productName:product.name,amount:product.price,name:input.name,email:input.email,phone:input.phone,dob:answers.dob,question:answers.question,intake,language:input.language,status:'pending_payment',createdAt:new Date().toISOString(),paidAt:null,dueAt:null,deliveredAt:null,paymentId:null,reportFile:null,customerNote:'',internalNote:'',assignedTo:''};db.prepare('INSERT INTO orders VALUES(?,?,?,NULL)').run(id,hash(token),JSON.stringify(order));audit('order.created',id);try{const session=await createPayment(order);res.status(201).json({id,access:token,paymentSessionId:session,mode:paymentMode()});}catch(error){order.status='cancelled';saveOrder(order);throw error;}});
 app.get('/api/orders/:id',publicLimit,(req,res)=>res.json(publicOrder(accessible(req))));
 app.post('/api/orders/:id/verify',publicLimit,async(req,res)=>{const order=accessible(req);if(order.status==='pending_payment')await verifyPayment(order.id);res.json(publicOrder(getOrder(order.id)!));});
 app.post('/api/orders/:id/pay',publicLimit,async(req,res)=>{const order=accessible(req);if(order.status!=='pending_payment')throw fail('This order is not awaiting payment.');const session=order.cashfreeSession||await createPayment(order);res.json({paymentSessionId:session,mode:paymentMode()});});
 app.get('/api/orders/:id/report',publicLimit,(req,res)=>{const order=accessible(req);if(order.status!=='delivered'||!order.reportFile)throw fail('Your report is not ready yet.',404);res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition',`attachment; filename="${order.id}-report.pdf"`);res.send(readFileSync(path.join(dataDir,'reports',order.reportFile)));});
 app.use('/api/admin',requireAdmin);
 app.get('/api/admin/overview',(_req,res)=>{const orders=allOrders();res.json({orders,counts:{pending:orders.filter(o=>['paid','preparing','review'].includes(o.status)).length,delivered:orders.filter(o=>o.status==='delivered').length,revenue:orders.filter(o=>o.paidAt&&o.status!=='refunded').reduce((s,o)=>s+o.amount,0),overdue:orders.filter(o=>o.dueAt&&new Date(o.dueAt)<new Date()&&!['delivered','refunded','cancelled'].includes(o.status)).length},payment:{configured:paymentConfigured(),mode:paymentMode(),enabled:settings().paymentsEnabled},emailConfigured:mailConfigured(),audit:db.prepare('SELECT * FROM audit ORDER BY at DESC LIMIT 15').all()});});
 app.get('/api/admin/content/:kind',(req,res)=>res.json(entries(kindOf(req.params.kind))));
 app.post('/api/admin/content/:kind',(req,res)=>{const kind=kindOf(req.params.kind);const item=schemas[kind].parse(req.body) as Entry;try{const result=saveEntry(kind,item);audit(item.published?'content.published':'content.saved',`${kind}/${item.id}`);res.json(result);}catch(error){if(String(error).includes('UNIQUE'))throw fail('An entry already exists for this date, location/sign and language. Edit that entry instead.',409);throw error;}});
 app.delete('/api/admin/content/:kind/:id',(req,res)=>{const kind=kindOf(req.params.kind);db.prepare('DELETE FROM content WHERE kind=? AND id=?').run(kind,req.params.id);audit('content.deleted',`${kind}/${req.params.id}`);res.json({ok:true});});
 app.post('/api/admin/images',upload.single('file'),async(req,res)=>{if(!req.file)throw fail('Choose a portrait image.');let buffer:Buffer;try{buffer=await sharp(req.file.buffer,{limitInputPixels:25000000}).rotate().resize(1000,1200,{fit:'inside',withoutEnlargement:true}).webp({quality:85}).toBuffer();}catch{throw fail('Upload a valid JPEG, PNG or WebP image under 10 MB.');}const filename=randomUUID()+'.webp';writeFileSync(path.join(dataDir,'images',filename),buffer);audit('image.uploaded',filename);res.status(201).json({url:'/api/media/'+filename});});
 app.get('/api/admin/settings',(_req,res)=>res.json(settings()));
 app.put('/api/admin/settings',(req,res)=>{const value=settingsSchema.parse(req.body);if(value.paymentsEnabled&&!paymentConfigured())throw fail('Configure your Cashfree server credentials before enabling payments.');if(value.paymentsEnabled&&!value.email)throw fail('Add a customer support email before enabling payments.');db.prepare('UPDATE settings SET data=? WHERE id=1').run(JSON.stringify(value));audit('settings.updated','site');res.json(value);});
 app.get('/api/admin/orders/:id',(req,res)=>{const order=getOrder(String(req.params.id));if(!order)throw fail('Order not found.',404);res.json({...order,mail:db.prepare('SELECT kind,status,at,error FROM mail WHERE order_id=? ORDER BY at DESC').all(order.id)});});
 app.patch('/api/admin/orders/:id',(req,res)=>{const order=getOrder(String(req.params.id));if(!order)throw fail('Order not found.',404);const input=z.object({status:z.enum(['pending_payment','paid','preparing','review','cancelled','refunded']).optional(),internalNote:z.string().max(5000).optional(),customerNote:z.string().max(2000).optional(),assignedTo:z.string().max(100).optional(),refundReference:z.string().max(200).optional()}).parse(req.body);const transitions:Record<OrderStatus,OrderStatus[]>={pending_payment:['cancelled'],paid:['preparing','refunded'],preparing:['review','refunded'],review:['preparing','refunded'],delivered:['refunded'],cancelled:[],refunded:[]};if(input.status&&input.status!==order.status&&!transitions[order.status].includes(input.status))throw fail('That status change is not allowed. Payment must be verified by Cashfree and reports released through the delivery action.');if(input.status==='refunded'&&order.status!=='refunded'&&!input.refundReference)throw fail('Complete the refund in Cashfree, then enter its reference to record it here.');const {refundReference,...changes}=input;Object.assign(order,changes);if(refundReference)order.internalNote+='\nRefund reference: '+refundReference;saveOrder(order);audit('order.updated',order.id);res.json(order);});
 app.post('/api/admin/orders/:id/verify',async(req,res)=>{const order=await verifyPayment(req.params.id);if(!order)throw fail('Order not found.',404);res.json(order);});
 app.post('/api/admin/orders/:id/report',upload.single('file'),(req,res)=>{const order=getOrder(String(req.params.id));if(!order)throw fail('Order not found.',404);if(!['paid','preparing','review'].includes(order.status))throw fail('Only paid, active orders can receive a report.');if(!req.file||req.file.buffer.subarray(0,5).toString()!=='%PDF-')throw fail('Choose a valid PDF under 10 MB.');const filename=randomUUID()+'.pdf';writeFileSync(path.join(dataDir,'reports',filename),req.file.buffer);order.reportFile=filename;order.status='review';saveOrder(order);audit('report.uploaded',order.id);res.json(order);});
 app.get('/api/admin/orders/:id/report',(req,res)=>{const order=getOrder(String(req.params.id));if(!order?.reportFile)throw fail('No report uploaded.',404);res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition','attachment; filename="review-report.pdf"');res.send(readFileSync(path.join(dataDir,'reports',order.reportFile)));});
 app.post('/api/admin/orders/:id/deliver',async(req,res)=>{const order=getOrder(String(req.params.id));if(!order)throw fail('Order not found.',404);if(order.status!=='review'||!order.reportFile)throw fail('Upload and review the PDF before releasing it.');if(req.body.confirmed!==true)throw fail('Confirm that this PDF belongs to this customer.');order.status='delivered';order.deliveredAt=new Date().toISOString();saveOrder(order);audit('report.delivered',order.id);const emailSent=await sendMail(order,'delivery');res.json({order,emailSent});});
 app.post('/api/admin/orders/:id/confirmation',async(req,res)=>{const order=getOrder(String(req.params.id));if(!order?.paidAt||['cancelled','refunded'].includes(order.status))throw fail('Only paid active orders can receive payment confirmation.');res.json({emailSent:await sendMail(order,'payment')});});
 app.post('/api/admin/orders/:id/resend',async(req,res)=>{const order=getOrder(String(req.params.id));if(!order||order.status!=='delivered')throw fail('Only delivered reports can be notified again.');const emailSent=await sendMail(order,'delivery');res.json({emailSent});});
 app.post('/api/admin/password',authLimit,(req,res)=>{const input=z.object({current:z.string().max(200),password:z.string().min(12).max(200)}).parse(req.body);const session=db.prepare('SELECT user_id FROM sessions WHERE hash=?').get(hash(req.cookies.nv_admin)) as {user_id:string};const user=db.prepare('SELECT password FROM users WHERE id=?').get(session.user_id) as {password:string};if(!passwordMatches(input.current,user.password))throw fail('Current password is incorrect.',401);db.prepare('UPDATE users SET password=? WHERE id=?').run(passwordHash(input.password),session.user_id);db.prepare('DELETE FROM sessions WHERE user_id=?').run(session.user_id);res.clearCookie('nv_admin',{path:'/'});audit('admin.password_changed',session.user_id);res.json({ok:true});});
 app.use((_req,res)=>res.status(404).json({error:'Not found.'}));
 app.use((error:unknown,_req:express.Request,res:express.Response,_next:express.NextFunction)=>{if(error instanceof ZodError)return res.status(400).json({error:error.issues.map(i=>(i.path.length?i.path.join('.')+': ':'')+i.message).join(' ')});if(error instanceof multer.MulterError)return res.status(400).json({error:'Upload one file under 10 MB.'});const e=error as {status?:number;message?:string};if(e.status)return res.status(e.status).json({error:e.message});console.error('API request failed:',error instanceof Error?error.message:'Unknown error');return res.status(500).json({error:'The request could not be completed. Please try again.'});});
 return app;
}



