import {activeFields} from '../lib/report-catalog';
import express from 'express';
import cookieParser from 'cookie-parser';
import helmet from 'helmet';
import {requestLimit} from './limits';
import multer from 'multer';
import sharp from 'sharp';
import {randomBytes,randomUUID} from 'node:crypto';
import {saveFile,readReport,localImage,portraitUrl,publicImagesOnCloud,uploadLimit} from './storage';
import {z,ZodError} from 'zod';
import {settings,setSettings,entries,saveEntry,deleteEntry,allOrders,getOrder,saveOrder,audit,recentAudit,orderHash,insertOrder,cancelPending,findUser,createSession,deleteSession,userById,changePassword,mailHistory,adminCount} from './store';
import {usesMongo} from './mongo';
import {hash,passwordHash,passwordMatches,requireAdmin,originGuard} from './security';
import {schemas,settingsSchema,orderSchema} from './schemas';
import {createPayment,verifyPayment,validWebhook,paymentConfigured,paymentMode} from './payments';
import {sendMail,mailConfigured} from './mail';
import type {Entry,Kind,Order,OrderStatus,Product} from '../lib/types';
const fail=(message:string,status=400)=>Object.assign(new Error(message),{status});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:uploadLimit,files:1,fields:5}});
const kindOf=(value:string):Kind=>{if(!Object.hasOwn(schemas,value))throw fail('Unknown content type.',404);return value as Kind;};
async function accessible(req:express.Request):Promise<Order>{const id=String(req.params.id);const token=req.headers.authorization?.replace(/^Bearer /,'')||'';if(!token||token.length>200)throw fail('Enter your order number and access code.',401);const savedHash=await orderHash(id);if(!savedHash||hash(token)!==savedHash)throw fail('Order number or access code is incorrect.',404);return (await getOrder(id))!;}
function publicOrder(order:Order){const {internalNote,reportFile,cashfreeSession,...safe}=order;return {...safe,hasReport:!!reportFile&&order.status==='delivered'};}
export function createApp(){
 const app=express();app.disable('x-powered-by');app.use(helmet({contentSecurityPolicy:false}));app.use(cookieParser());
 app.use('/api',(_req,res,next)=>{res.setHeader('Cache-Control','no-store');next();});
 app.post('/api/payments/cashfree/webhook',express.raw({type:'application/json',limit:'256kb'}),async(req,res)=>{
  if(!Buffer.isBuffer(req.body)||!validWebhook(req.body,String(req.headers['x-webhook-timestamp']||''),String(req.headers['x-webhook-signature']||'')))return res.status(401).json({error:'Invalid signature.'});
  const event=JSON.parse(req.body.toString());const id=event?.data?.order?.order_id;
  if(typeof id==='string'&&await getOrder(id))await verifyPayment(id);
  res.json({received:true});
 });
 app.use(express.json({limit:'128kb'}));app.use(originGuard);
 const authLimit=requestLimit('auth',20);
 const publicLimit=requestLimit('orders',120);
 app.get('/api/health',async(_req,res)=>{await settings();res.json({ok:true,store:usesMongo()?'mongodb':'sqlite',adminConfigured:(await adminCount())>0});});
 app.get('/api/public',async(_req,res)=>{const published=async(kind:Kind)=>(await entries(kind)).filter(x=>x.published).sort((a,b)=>Number(a.order||0)-Number(b.order||0));res.json({settings:(await settings()),products:await published('products'),experts:await published('experts'),testimonials:await published('testimonials'),panchang:(await published('panchang')).map(({source,...p})=>p),horoscopes:await published('horoscopes'),payment:{configured:paymentConfigured(),enabled:(await settings()).paymentsEnabled,mode:paymentMode()}});});
 app.get('/api/media/:file',async(req,res)=>{if(!/^[a-f0-9-]+\.webp$/.test(req.params.file))throw fail('Image not found.',404);res.setHeader('Cache-Control','public,max-age=86400');if(publicImagesOnCloud())res.redirect(302,portraitUrl(req.params.file));else res.sendFile(await localImage(req.params.file));});
 app.post('/api/auth/login',authLimit,async(req,res)=>{const input=z.object({email:z.email(),password:z.string().min(1).max(200)}).parse(req.body);const user=await findUser(input.email.toLowerCase());const dummy='00'.repeat(16)+':'+'00'.repeat(64);if(!passwordMatches(input.password,user?.password||dummy)||!user){if(!await adminCount())throw fail('No administrator account exists yet in this database. Run npm run admin:create against it, then sign in.',401);throw fail('Email or password is incorrect.',401);}const token=randomBytes(32).toString('hex');await createSession(hash(token),user.id);res.cookie('nv_admin',token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'strict',path:'/',maxAge:8*3600000});await audit('admin.login',user.id);res.json({ok:true});});
 app.post('/api/auth/logout',async(req,res)=>{if(req.cookies.nv_admin)await deleteSession(hash(req.cookies.nv_admin));res.clearCookie('nv_admin',{path:'/',httpOnly:true,sameSite:'strict',secure:process.env.NODE_ENV==='production'});res.json({ok:true});});
 app.get('/api/auth/me',requireAdmin,async(_req,res)=>res.json({authenticated:true}));
 app.post('/api/report-intake/validate',publicLimit,async(req,res)=>{const input=orderSchema.parse(req.body);if(!(await entries('products')).some(p=>p.id===input.productId&&p.published))throw fail('This report is not available.',404);res.json({ok:true});});
 app.post('/api/orders',publicLimit,async(req,res)=>{const input=orderSchema.parse(req.body);if(!(await settings()).paymentsEnabled||!paymentConfigured())throw fail('Online payments are not open yet. Please contact us or check back shortly.',503);const product=(await entries('products')).find(p=>p.id===input.productId&&p.published) as Product|undefined;if(!product)throw fail('This report is not available.',404);const answers:Record<string,string>={...input.answers,dob:input.answers.dob||input.dob,question:input.answers.question||input.question};const intake=activeFields(product.id,answers).filter(f=>answers[f.key]).map(f=>({label:f.label,value:answers[f.key]}));const token=randomBytes(24).toString('hex');const id='NV_'+randomBytes(10).toString('hex');const order:Order={id,productId:product.id,productName:product.name,amount:product.price,name:input.name,email:input.email,phone:input.phone,dob:answers.dob,question:answers.question,intake,language:input.language,status:'pending_payment',createdAt:new Date().toISOString(),paidAt:null,dueAt:null,deliveredAt:null,paymentId:null,reportFile:null,customerNote:'',internalNote:'',assignedTo:''};await insertOrder(order,hash(token));await audit('order.created',id);try{const session=await createPayment(order);res.status(201).json({id,access:token,paymentSessionId:session,mode:paymentMode()});}catch(error){await cancelPending(id);throw error;}});
 app.get('/api/orders/:id',publicLimit,async(req,res)=>res.json(publicOrder(await accessible(req))));
 app.post('/api/orders/:id/verify',publicLimit,async(req,res)=>{const order=await accessible(req);if(order.status==='pending_payment')await verifyPayment(order.id);res.json(publicOrder((await getOrder(order.id))!));});
 app.post('/api/orders/:id/pay',publicLimit,async(req,res)=>{const order=await accessible(req);if(order.status!=='pending_payment')throw fail('This order is not awaiting payment.');const session=order.cashfreeSession||await createPayment(order);res.json({paymentSessionId:session,mode:paymentMode()});});
 app.get('/api/orders/:id/report',publicLimit,async(req,res)=>{const order=await accessible(req);if(order.status!=='delivered'||!order.reportFile)throw fail('Your report is not ready yet.',404);res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition',`attachment; filename="${order.id}-report.pdf"`);res.send(await readReport(order.reportFile));});
 app.use('/api/admin',requireAdmin);
 app.get('/api/admin/overview',async(_req,res)=>{const orders=await allOrders();res.json({orders,counts:{pending:orders.filter(o=>['paid','preparing','review'].includes(o.status)).length,delivered:orders.filter(o=>o.status==='delivered').length,revenue:orders.filter(o=>o.paidAt&&o.status!=='refunded').reduce((s,o)=>s+o.amount,0),overdue:orders.filter(o=>o.dueAt&&new Date(o.dueAt)<new Date()&&!['delivered','refunded','cancelled'].includes(o.status)).length},payment:{configured:paymentConfigured(),mode:paymentMode(),enabled:(await settings()).paymentsEnabled},emailConfigured:mailConfigured(),audit:await recentAudit()});});
 app.get('/api/admin/content/:kind',async(req,res)=>res.json(await entries(kindOf(req.params.kind))));
 app.post('/api/admin/content/:kind',async(req,res)=>{const kind=kindOf(req.params.kind);const item=schemas[kind].parse(req.body) as Entry;try{const result=await saveEntry(kind,item);await audit(item.published?'content.published':'content.saved',`${kind}/${item.id}`);res.json(result);}catch(error){if(String(error).includes('UNIQUE'))throw fail('An entry already exists for this date, location/sign and language. Edit that entry instead.',409);throw error;}});
 app.delete('/api/admin/content/:kind/:id',async(req,res)=>{const kind=kindOf(req.params.kind);await deleteEntry(kind,req.params.id);await audit('content.deleted',`${kind}/${req.params.id}`);res.json({ok:true});});
 app.post('/api/admin/images',upload.single('file'),async(req,res)=>{if(!req.file)throw fail('Choose a portrait image.');let buffer:Buffer;try{buffer=await sharp(req.file.buffer,{limitInputPixels:25000000}).rotate().resize(1000,1200,{fit:'inside',withoutEnlargement:true}).webp({quality:85}).toBuffer();}catch{throw fail('Upload a valid JPEG, PNG or WebP image under 4 MB.');}const filename=await saveFile('images',buffer);await audit('image.uploaded',filename);res.status(201).json({url:'/api/media/'+filename});});
 app.get('/api/admin/settings',async(_req,res)=>res.json((await settings())));
 app.put('/api/admin/settings',async(req,res)=>{const value=settingsSchema.parse(req.body);if(value.paymentsEnabled&&!paymentConfigured())throw fail('Configure your Cashfree server credentials before enabling payments.');if(value.paymentsEnabled&&!value.email)throw fail('Add a customer support email before enabling payments.');await setSettings(value);await audit('settings.updated','site');res.json(value);});
 app.get('/api/admin/orders/:id',async(req,res)=>{const order=await getOrder(String(req.params.id));if(!order)throw fail('Order not found.',404);res.json({...order,mail:await mailHistory(order.id)});});
 app.patch('/api/admin/orders/:id',async(req,res)=>{const order=await getOrder(String(req.params.id));if(!order)throw fail('Order not found.',404);const input=z.object({status:z.enum(['pending_payment','paid','preparing','review','cancelled','refunded']).optional(),internalNote:z.string().max(5000).optional(),customerNote:z.string().max(2000).optional(),assignedTo:z.string().max(100).optional(),refundReference:z.string().max(200).optional()}).parse(req.body);const transitions:Record<OrderStatus,OrderStatus[]>={pending_payment:['cancelled'],paid:['preparing','refunded'],preparing:['review','refunded'],review:['preparing','refunded'],delivered:['refunded'],cancelled:[],refunded:[]};if(input.status&&input.status!==order.status&&!transitions[order.status].includes(input.status))throw fail('That status change is not allowed. Payment must be verified by Cashfree and reports released through the delivery action.');if(input.status==='refunded'&&order.status!=='refunded'&&!input.refundReference)throw fail('Complete the refund in Cashfree, then enter its reference to record it here.');const {refundReference,...changes}=input;Object.assign(order,changes);if(refundReference)order.internalNote+='\nRefund reference: '+refundReference;await saveOrder(order);await audit('order.updated',order.id);res.json(order);});
 app.post('/api/admin/orders/:id/verify',async(req,res)=>{const order=await verifyPayment(req.params.id);if(!order)throw fail('Order not found.',404);res.json(order);});
 app.post('/api/admin/orders/:id/report',upload.single('file'),async(req,res)=>{const order=await getOrder(String(req.params.id));if(!order)throw fail('Order not found.',404);if(!['paid','preparing','review'].includes(order.status))throw fail('Only paid, active orders can receive a report.');if(!req.file||req.file.buffer.subarray(0,5).toString()!=='%PDF-')throw fail('Choose a valid PDF under 4 MB.');const filename=await saveFile('reports',req.file.buffer);order.reportFile=filename;order.status='review';await saveOrder(order);await audit('report.uploaded',order.id);res.json(order);});
 app.get('/api/admin/orders/:id/report',async(req,res)=>{const order=await getOrder(String(req.params.id));if(!order?.reportFile)throw fail('No report uploaded.',404);res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition','attachment; filename="review-report.pdf"');res.send(await readReport(order.reportFile));});
 app.post('/api/admin/orders/:id/deliver',async(req,res)=>{const order=await getOrder(String(req.params.id));if(!order)throw fail('Order not found.',404);if(order.status!=='review'||!order.reportFile)throw fail('Upload and review the PDF before releasing it.');if(req.body.confirmed!==true)throw fail('Confirm that this PDF belongs to this customer.');order.status='delivered';order.deliveredAt=new Date().toISOString();await saveOrder(order);await audit('report.delivered',order.id);const emailSent=await sendMail(order,'delivery');res.json({order,emailSent});});
 app.post('/api/admin/orders/:id/confirmation',async(req,res)=>{const order=await getOrder(String(req.params.id));if(!order?.paidAt||['cancelled','refunded'].includes(order.status))throw fail('Only paid active orders can receive payment confirmation.');res.json({emailSent:await sendMail(order,'payment')});});
 app.post('/api/admin/orders/:id/resend',async(req,res)=>{const order=await getOrder(String(req.params.id));if(!order||order.status!=='delivered')throw fail('Only delivered reports can be notified again.');const emailSent=await sendMail(order,'delivery');res.json({emailSent});});
 app.post('/api/admin/password',authLimit,async(req,res)=>{const input=z.object({current:z.string().max(200),password:z.string().min(12).max(200)}).parse(req.body);const userId=res.locals.userId as string;const user=await userById(userId);if(!user||!passwordMatches(input.current,user.password))throw fail('Current password is incorrect.',401);await changePassword(userId,passwordHash(input.password));res.clearCookie('nv_admin',{path:'/'});await audit('admin.password_changed',userId);res.json({ok:true});});
 app.use(async(_req,res)=>res.status(404).json({error:'Not found.'}));
 app.use((error:unknown,_req:express.Request,res:express.Response,_next:express.NextFunction)=>{if(error instanceof ZodError)return res.status(400).json({error:error.issues.map(i=>(i.path.length?i.path.join('.')+': ':'')+i.message).join(' ')});if(error instanceof multer.MulterError)return res.status(400).json({error:'Upload one file under 4 MB.'});const e=error as {status?:number;message?:string};if(e.status)return res.status(e.status).json({error:e.message});console.error('API request failed:',error instanceof Error?error.name:'Unknown error');return res.status(500).json({error:'The request could not be completed. Please try again.'});});
 return app;
}



