import {sendMail} from './mail';
import {createHmac} from 'node:crypto';
import {equal} from './security';
import {getOrder,paymentSession,audit,settings,recordPayment} from './store';
import type {Order} from '../lib/types';
export const paymentMode=()=>process.env.CASHFREE_ENV==='production'?'production':'sandbox';
export const paymentConfigured=()=>!!(process.env.CASHFREE_CLIENT_ID&&process.env.CASHFREE_CLIENT_SECRET);
async function cashfree(endpoint:string,method='GET',body?:unknown){
 const response=await fetch((paymentMode()==='production'?'https://api.cashfree.com/pg':'https://sandbox.cashfree.com/pg')+endpoint,{method,headers:{'x-client-id':process.env.CASHFREE_CLIENT_ID||'','x-client-secret':process.env.CASHFREE_CLIENT_SECRET||'','x-api-version':'2025-01-01','Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(20000)});
 const data=await response.json();if(!response.ok)throw Object.assign(new Error('Cashfree could not process this request. Please try again or contact support.'),{status:502});return data;
}
export async function createPayment(order:Order){if(!paymentConfigured()||!(await settings()).paymentsEnabled)throw Object.assign(new Error('Online payments are not available yet. Please check back shortly.'),{status:503});const origin=process.env.APP_ORIGIN||'http://localhost:3000';const result=await cashfree('/orders','POST',{order_id:order.id,order_amount:order.amount/100,order_currency:'INR',customer_details:{customer_id:order.id,customer_name:order.name,customer_email:order.email,customer_phone:order.phone},order_meta:{return_url:`${origin}/track?order=${order.id}`}});order.cashfreeSession=result.payment_session_id;await paymentSession(order.id,result.payment_session_id);return result.payment_session_id as string;}
export async function markPaid(id:string,paymentId:string,paidAt?:string){const at=paidAt&&Number.isFinite(Date.parse(paidAt))?new Date(paidAt):new Date();if(at.getTime()>Date.now()+300000)throw new Error('Invalid payment time');const order=await recordPayment(id,paymentId,at);await audit('payment.verified',id);return order;}
export async function verifyPayment(id:string){const order=await getOrder(id);if(!order||!paymentConfigured())return order;if(order.paidAt){if(!['cancelled','refunded'].includes(order.status))await sendMail(order,'payment');return order;}const remote=await cashfree('/orders/'+encodeURIComponent(id));if(remote.order_status==='PAID'&&remote.order_currency==='INR'&&Math.round(Number(remote.order_amount)*100)===order.amount){const payments=await cashfree('/orders/'+encodeURIComponent(id)+'/payments');const success=payments.find((p:{payment_status:string;payment_amount:number;payment_currency:string})=>p.payment_status==='SUCCESS'&&p.payment_currency==='INR'&&Math.round(p.payment_amount*100)===order.amount);if(success){const paid=await markPaid(id,String(success.cf_payment_id),success.payment_completion_time||success.payment_time);await sendMail(paid,'payment');return paid;}}return order;}
export function validWebhook(raw:Buffer,timestamp:string,signature:string){if(!process.env.CASHFREE_CLIENT_SECRET||!timestamp||!signature)return false;const expected=createHmac('sha256',process.env.CASHFREE_CLIENT_SECRET).update(timestamp).update(raw).digest('base64');return equal(expected,signature);}
