export type IntakeField={key:string;label:string;type?:'text'|'textarea'|'date'|'time'|'number'|'month'|'select'|'multi';required?:boolean;options?:string[];when?:[string,string];hint?:string};
const f=(key:string,label:string,required=false,type:IntakeField['type']='text',options?:string[]):IntakeField=>({key,label,required,type,options});
const focus=(options:string[])=>f('focus','Where should the numerologist focus? Choose up to 3.',true,'multi',options);
const when=(field:IntakeField,key:string,value:string):IntakeField=>({...field,when:[key,value]});
const dob=f('dob','Date of birth',true,'date');
const question=(label='Main question')=>f('question',label,false,'textarea');
export const reportCatalog:{id:string;name:string;description:string;features:string[];fields:IntakeField[]}[]=[
 {id:'personal-numerology',name:'Individual Life',description:'Explore your personal numbers, life themes, and the questions that matter most to you.',features:['Birth & life-path analysis','Personal areas of focus','Your life questions considered','Human-reviewed PDF'],fields:[dob,question('Anything you would like guidance on?')]},
 {id:'relationship-compatibility',name:'Relationship Compatibility',description:'Understand the numerological patterns between two people and what you hope to improve together.',features:['Both partners’ core numbers','Compatibility interpretation','Relationship concerns & goals','Human-reviewed PDF'],fields:[f('personOne','First partner’s full name',true),f('dobOne','First partner’s date of birth',true,'date'),f('personTwo','Second partner’s full name',true),f('dobTwo','Second partner’s date of birth',true,'date'),question('What should we focus on in your relationship?')]},
 {id:'marriage-date',name:'Marriage Date & Muhurat',description:'Explore a numerological wedding date or request an astrological muhurat using both partners’ complete birth details.',features:['Preferred date-range review','Wedding location & restrictions','Numerology or astrology selection','Human-reviewed PDF'],fields:[f('personOne','First partner’s full name',true),f('dobOne','First partner’s date of birth',true,'date'),f('personTwo','Second partner’s full name',true),f('dobTwo','Second partner’s date of birth',true,'date'),f('dateFrom','Preferred dates: from',true,'date'),f('dateTo','Preferred dates: to',true,'date'),f('city','Wedding city / country',true),f('method','Date selection',true,'select',['Numerological date selection','Astrological muhurat']),...['One','Two'].flatMap(n=>[when(f('birthTime'+n,`${n==='One'?'First':'Second'} partner’s birth time`,true,'time'),'method','Astrological muhurat'),when(f('birthplace'+n,`${n==='One'?'First':'Second'} partner’s birthplace`,true),'method','Astrological muhurat')]),question('Any dates or restrictions we should consider?')]},
 {id:'baby-name',name:'Baby Name',description:'Compare baby names or explore suggestions that reflect your language, surname, and family traditions.',features:['Name comparison or suggestions','Language & surname preferences','Meanings and family traditions','Human-reviewed PDF'],fields:[f('babyStatus','Is your baby born or expected?',true,'select',['Born','Expecting']),when(f('babyDob','Baby’s date of birth',true,'date'),'babyStatus','Born'),f('surname','Baby’s surname',true),f('preferredLanguage','Preferred name language',true),f('namingMode','What would you like?',true,'select',['Compare existing names','Request suggestions']),when(f('names','Names you have in mind',true,'textarea'),'namingMode','Compare existing names'),question('Any preferred letters, meanings or names?')]},
 {id:'name-analysis',name:'Name Correction',description:'Review your current name and preferred spellings, with the parts of your identity you want to preserve.',features:['Current & birth-name review','Name and birth-date alignment','Preferred spellings considered','Human-reviewed PDF'],fields:[dob,f('birthName','Birth name, only if different'),question('Why are you considering a change? Include any parts to keep.')]},
 {id:'career-money',name:'Career & Money',description:'Explore your work and study direction through your personal numbers, priorities, and current challenges.',features:['Personal numerology interpretation','Work or study priorities','Career options & goals','Human-reviewed PDF'],fields:[dob,f('workStatus','Current work / study status',true),question('What career or money question should we focus on?')]},
 {id:'business-name',name:'Business Name',description:'Compare business names or request suggestions suited to your industry, audience, and naming preferences.',features:['Name comparison or suggestions','Industry & audience context','Founder details considered','Human-reviewed PDF'],fields:[f('industry','What does your business do?',true),f('namingMode','What would you like?',true,'select',['Compare names','Request suggestions']),when(f('names','Business names to compare',true,'textarea'),'namingMode','Compare names'),question('Any naming preferences or important details?')]},
 {id:'mobile-vehicle',name:'Mobile & Vehicle Number Check',description:'Explore the numerological interpretation of a mobile number or vehicle registration and possible alternatives.',features:['Mobile or vehicle number review','Your main question considered','Optional alternative comparison','Human-reviewed PDF'],fields:[f('numberType','Mobile or vehicle?',true,'select',['Mobile','Vehicle']),{...f('number','Number / registration to check',true),hint:'No OTPs or identity documents.'},question('Any alternatives or a specific question?')]},
 {id:'yearly-forecast',name:'Yearly Personal Forecast',description:'Explore the themes of your personal year alongside your priorities and planned milestones.',features:['Personal-year interpretation','Priority areas & milestones','Your questions considered','Human-reviewed PDF'],fields:[dob,f('targetYear','Year for your forecast',true,'number'),question('What would you most like guidance on this year?')]},
];
export function reportDefinition(id:string){return reportCatalog.find(r=>r.id===id);}
export function activeFields(id:string,answers:Record<string,string>){return reportDefinition(id)?.fields.filter(f=>!f.when||answers[f.when[0]]===f.when[1])||[];}
