export type IntakeField={key:string;label:string;type?:'text'|'textarea'|'date'|'time'|'number'|'month'|'select'|'multi';required?:boolean;options?:string[];when?:[string,string];hint?:string};
const f=(key:string,label:string,required=false,type:IntakeField['type']='text',options?:string[]):IntakeField=>({key,label,required,type,options});
const focus=(options:string[])=>f('focus','Where should the numerologist focus? Choose up to 3.',true,'multi',options);
const when=(field:IntakeField,key:string,value:string):IntakeField=>({...field,when:[key,value]});
const dob=f('dob','Date of birth',true,'date');
const question=(label='Main question')=>f('question',label,true,'textarea');
export const reportCatalog:{id:string;name:string;description:string;features:string[];fields:IntakeField[]}[]=[
 {id:'personal-numerology',name:'Individual Life',description:'Explore your personal numbers, life themes, and the questions that matter most to you.',features:['Birth & life-path analysis','Personal areas of focus','Your life questions considered','Human-reviewed PDF'],fields:[dob,question('What would you most like to understand about your life?'),f('birthName','Birth name, if different'),f('situation','Current situation',false,'textarea'),focus(['Personality','Relationships','Career','Personal growth','Other'])]},
 {id:'relationship-compatibility',name:'Relationship Compatibility',description:'Understand the numerological patterns between two people and what you hope to improve together.',features:['Both partners’ core numbers','Compatibility interpretation','Relationship concerns & goals','Human-reviewed PDF'],fields:[f('personOne','First person’s full name',true),f('dobOne','First person’s date of birth',true,'date'),f('personTwo','Second person’s full name',true),f('dobTwo','Second person’s date of birth',true,'date'),f('stage','Relationship stage',true,'select',['Getting to know each other','Dating','Engaged','Married','Other']),focus(['Communication','Emotional connection','Recurring conflict','Marriage compatibility','Other']),question(),f('duration','Relationship duration'),f('concerns','Recurring concerns',false,'textarea'),f('improve','What do you hope to improve?',false,'textarea')]},
 {id:'marriage-date',name:'Marriage Date & Muhurat',description:'Explore a numerological wedding date or request an astrological muhurat using both partners’ complete birth details.',features:['Preferred date-range review','Wedding location & restrictions','Numerology or astrology selection','Human-reviewed PDF'],fields:[f('personOne','First person’s full name',true),f('dobOne','First person’s date of birth',true,'date'),f('personTwo','Second person’s full name',true),f('dobTwo','Second person’s date of birth',true,'date'),f('dateFrom','Preferred range: from',true,'date'),f('dateTo','Preferred range: to',true,'date'),f('city','Wedding city / country',true),f('method','Type of date selection',true,'select',['Numerological date selection','Astrological muhurat']),...['One','Two'].flatMap((n)=>[{...f('birthTime'+n,`${n==='One'?'First':'Second'} person’s birth time`,true,'time'),when:['method','Astrological muhurat'] as [string,string]},{...f('birthplace'+n,`${n==='One'?'First':'Second'} person’s birthplace (city / country)`,true),when:['method','Astrological muhurat'] as [string,string]}]),f('shortlist','Shortlisted dates'),f('restrictions','Unavailable dates, family or scheduling preferences',false,'textarea')]},
 {id:'baby-name',name:'Baby Name',description:'Compare baby names or explore suggestions that reflect your language, surname, and family traditions.',features:['Name comparison or suggestions','Language & surname preferences','Meanings and family traditions','Human-reviewed PDF'],fields:[f('babyStatus','Born or expecting?',true,'select',['Born','Expecting']),f('surname','Surname',true),f('preferredLanguage','Preferred language',true),f('namingMode','What would you like?',true,'select',['Compare existing names','Request suggestions']),{...f('babyDob','Baby’s date of birth',true,'date'),when:['babyStatus','Born'] as [string,string]},when({...f('dueMonth','Expected due month',false,'month'),hint:'An estimate only, not the actual date of birth.'},'babyStatus','Expecting'),f('thoughtOfNames','Have you already thought of any names?',true,'select',['Yes','No']),when(f('names','Shortlisted names',true,'textarea'),'namingMode','Compare existing names'),when(f('ideas','Names you have thought of',false,'textarea'),'namingMode','Request suggestions'),f('letters','Preferred starting letters'),when(f('style','Preferred naming style',true,'select',['Traditional','Modern','Short','Unisex','No preference']),'namingMode','Request suggestions'),f('meanings','Desired meanings'),f('traditions','Family traditions',false,'textarea'),f('avoid','Names to avoid')]},
 {id:'name-analysis',name:'Name Correction',description:'Review your current name and preferred spellings, with the parts of your identity you want to preserve.',features:['Current & birth-name review','Name and birth-date alignment','Preferred spellings considered','Human-reviewed PDF'],fields:[f('birthNameSame','Is your birth name the same as your current full name?',true,'select',['Yes','No']),when(f('birthName','Birth name',true),'birthNameSame','No'),dob,question('Reason for considering a name change'),f('spellings','Preferred spellings'),f('preserve','Which parts of your name must stay unchanged?',true),f('professionalName','Professional name'),f('pronunciation','Pronunciation preferences'),f('previousChanges','Previous name changes')]},
 {id:'career-money',name:'Career & Money',description:'Explore your work and study direction through your personal numbers, priorities, and current challenges.',features:['Personal numerology interpretation','Work or study priorities','Career options & goals','Human-reviewed PDF'],fields:[dob,f('workStatus','Current work / study status',true),focus(['Career direction','Job change','Business','Work satisfaction','Money habits','Other']),question(),f('options','Career options being considered',false,'textarea'),f('goals','Goals',false,'textarea'),f('challenges','Current challenges',false,'textarea'),f('milestones','Planned milestones',false,'textarea')]},
 {id:'business-name',name:'Business Name',description:'Compare business names or request suggestions suited to your industry, audience, and naming preferences.',features:['Name comparison or suggestions','Industry & audience context','Founder details considered','Human-reviewed PDF'],fields:[f('industry','Industry',true),f('businessStage','New or existing business?',true,'select',['New business','Existing business']),f('namingMode','What would you like?',true,'select',['Compare names','Request suggestions']),question('What is your main naming goal?'),when(f('names','Proposed names to compare',true,'textarea'),'namingMode','Compare names'),f('founder','Founder’s name'),f('founderDob','Founder’s date of birth',false,'date'),f('audience','Target audience'),when(f('preferences','Naming preferences',true,'textarea'),'namingMode','Request suggestions'),f('preferredLanguage','Preferred language / style'),f('words','Words to include or avoid'),when(f('existingName','Existing brand name'),'businessStage','Existing business')]},
 {id:'mobile-vehicle',name:'Mobile & Vehicle Number Check',description:'Explore the numerological interpretation of a mobile number or vehicle registration and possible alternatives.',features:['Mobile or vehicle number review','Your main question considered','Optional alternative comparison','Human-reviewed PDF'],fields:[f('numberType','Mobile or vehicle?',true,'select',['Mobile','Vehicle']),{...f('number','Number / registration to check',true),hint:'Enter only the number or registration. Never share OTPs or identity documents.'},f('comparison','Review one number or compare alternatives?',true,'select',['Review one number','Compare alternatives']),question(),f('owner','Owner’s name'),f('ownerDob','Owner’s date of birth',false,'date'),when(f('alternatives','Alternative numbers',true,'textarea'),'comparison','Compare alternatives'),f('usage','Personal or business use?',false,'select',['Personal','Business','Both'])]},
 {id:'yearly-forecast',name:'Yearly Personal Forecast',description:'Explore the themes of your personal year alongside your priorities and planned milestones.',features:['Personal-year interpretation','Priority areas & milestones','Your questions considered','Human-reviewed PDF'],fields:[dob,f('targetYear','Target year',true,'number'),focus(['Career','Relationships','Family','Personal growth','Money habits','Other']),question('What would you most like guidance on this year?'),f('milestones','Planned milestones',false,'textarea'),f('situation','Current situation',false,'textarea'),f('months','Specific months or events of interest')]}
];
export function reportDefinition(id:string){return reportCatalog.find(r=>r.id===id);}
export function activeFields(id:string,answers:Record<string,string>){return reportDefinition(id)?.fields.filter(f=>!f.when||answers[f.when[0]]===f.when[1])||[];}
